import {groupMetrics,toneClass,formatFire} from './ui-core.js?v=1';
import {metricExplanation,shipExplanation} from './explanations.js?v=1';
const BASE='https://aropywroudfriiqbmwhp.supabase.co/functions/v1';
const AUTH=BASE+'/starship-v3-mobile-auth';
const DATA=BASE+'/starship-v3-mobile-data';
const DK='sv3_device',SK='sv2',PK='sv2_persist';
const nativeFetch=window.fetch.bind(window);
const $=id=>document.getElementById(id);
const boot=$('boot'),gate=$('gate'),error=$('error'),code=$('code'),enter=$('enter'),err=$('err'),errtxt=$('errtxt'),retry=$('retry'),app=$('app'),cards=$('cards'),fireLine=$('fireLine'),updated=$('updated'),sectionTitle=$('sectionTitle'),drawer=$('drawer'),drawerTitle=$('drawerTitle'),drawerBody=$('drawerBody'),closeDrawer=$('closeDrawer'),shipStatus=$('shipStatus');
let renewing=false,dashboard=null,activeGroup='flow';
const LANE_KEYS=new Set(['p2','hold','p22','p11','auto','captcha','login','tech','serve','p3']);
function saveSession(t){sessionStorage.setItem(SK,t);localStorage.setItem(PK,t)}
function getSession(){return sessionStorage.getItem(SK)||localStorage.getItem(PK)||''}
function clearSession(){sessionStorage.removeItem(SK);localStorage.removeItem(PK)}
function showGate(msg=''){clearSession();boot.hidden=true;error.hidden=true;app.hidden=true;gate.hidden=false;err.textContent=msg;enter.disabled=false}
function showError(msg){boot.hidden=true;gate.hidden=true;app.hidden=true;error.hidden=false;errtxt.textContent=msg||'Riprova tra poco. Il telefono resta autorizzato.'}
async function fetchTimeout(url,opts={},ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await nativeFetch(url,{...opts,signal:c.signal})}finally{clearTimeout(t)}}
async function sessionFromDevice(){const d=localStorage.getItem(DK);if(!d)return{kind:'NO_DEVICE'};try{const r=await fetchTimeout(AUTH+'/session',{method:'POST',headers:{authorization:'Bearer '+d,'content-type':'application/json'},cache:'no-store'});const z=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem(DK);clearSession();return{kind:'REVOKED'}}if(!r.ok||!z.session_token)return{kind:'TEMP',message:z.error||('HTTP '+r.status)};saveSession(z.session_token);return{kind:'OK'}}catch(e){return{kind:'TEMP',message:e?.name==='AbortError'?'timeout autenticazione':(e?.message||String(e))}}}
async function enroll(){const v=String(code.value||'').trim();if(!v)return;enter.disabled=true;err.textContent='';try{const r=await fetchTimeout(AUTH+'/enroll',{method:'POST',headers:{'x-pair-code':v,'content-type':'application/json'},cache:'no-store'});const z=await r.json().catch(()=>({}));if(!r.ok||!z.device_token||!z.session_token)throw Error(z.error||'Abbinamento non riuscito');localStorage.setItem(DK,z.device_token);saveSession(z.session_token);await openDashboard()}catch(e){err.textContent=e?.message||'Abbinamento non riuscito';enter.disabled=false}}
async function api(path){let token=getSession();let r=await fetchTimeout(DATA+path,{headers:{authorization:'Bearer '+token},cache:'no-store'});if(r.status===401&&!renewing){renewing=true;const q=await sessionFromDevice();renewing=false;if(q.kind==='OK'){token=getSession();r=await fetchTimeout(DATA+path,{headers:{authorization:'Bearer '+token},cache:'no-store'})}else if(q.kind==='REVOKED'||q.kind==='NO_DEVICE'){showGate('Telefono da abbinare');throw Error('device revoked')}}const z=await r.json().catch(()=>({}));if(!r.ok)throw Error(z.error||('HTTP '+r.status));return z}
const GROUPS={flow:'FLUSSO',alerts:'ANOMALIE',forms:'FORM',weapons:'ARSENALE & P3',results:'RISULTATI'};
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderGroup(group){activeGroup=group;document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.group===group));sectionTitle.textContent=GROUPS[group]||group;const grouped=groupMetrics(dashboard?.metrics||[]),list=grouped[group]||[];cards.innerHTML=list.map(m=>`<button class="metric ${toneClass(m.tone)}" data-key="${m.key}"><span class="metricTop"><b>${escapeHtml(m.title)}</b><strong>${Number(m.count||0)}</strong></span><small>${escapeHtml(m.subtitle||'Tocca per capire')}</small></button>`).join('')||'<div class="empty">Nessun dato.</div>'}
async function openDashboard(){gate.hidden=true;error.hidden=true;boot.hidden=false;boot.textContent='STARSHIP · CARICAMENTO V4…';try{dashboard=await api('/dashboard');fireLine.textContent=formatFire(dashboard.fire||{});updated.textContent='Aggiornato '+new Date(dashboard.updated_at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})+' · tocca per capire';boot.hidden=true;app.hidden=false;renderGroup(activeGroup)}catch(e){if(String(e.message).includes('device revoked'))return;showError('Errore V4: '+e.message)}}
function section(title,body){return `<section class="explain"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(body)}</p></section>`}
function actionButtons(actions,title){return `<section class="explain"><h3>COSA PUOI FARE</h3><div class="actions">${(actions||[]).map(a=>`<button class="actionBtn" data-action="${escapeHtml(a)}" data-context="${escapeHtml(title)}">${escapeHtml(a)}</button>`).join('')}</div><textarea id="commandDraft" class="draft" placeholder="Bozza comando o domanda…"></textarea><div class="draftNote">La bozza non viene eseguita automaticamente: serve solo a preparare il prossimo comando.</div></section>`}
function rowHtml(r){return `<div class="row"><b>${escapeHtml(r.display_name||r.company_name||r.name||r.company_id||'Record')}</b><span>${escapeHtml(r.status||r.p3_status||r.canonical_exit||r.gate_reason||'')}</span><small>${escapeHtml(r.problem_type||r.qa_status||r.last_error||r.route_target||r.lane||'')}</small></div>`}
async function openMetric(key){const m=(dashboard?.metrics||[]).find(x=>x.key===key);if(!m)return;const x=metricExplanation(m);drawer.hidden=false;drawerTitle.textContent=m.title;drawerBody.innerHTML=section("COS'È",x.what)+section('STATO ADESSO',x.now)+section('PERCHÉ',x.why)+`<section class="explain"><h3>COSA C'È DENTRO</h3><div id="inside"><div class="empty">Lettura dati…</div></div></section>`+actionButtons(x.actions,m.title);
 const inside=$('inside');if(!LANE_KEYS.has(key)){inside.innerHTML='<div class="empty">Questa scheda è un indicatore sintetico. Il dettaglio elenco non è ancora esposto nella V4.</div>';return}
 try{const z=await api('/lane?key='+encodeURIComponent(key));const rows=z.items||[];inside.innerHTML=rows.length?rows.map(rowHtml).join(''):'<div class="empty">Corsia vuota.</div>'}catch(e){inside.innerHTML=`<div class="empty">Dettaglio non disponibile: ${escapeHtml(e.message)}</div>`}}
function openShipStatus(){if(!dashboard)return;const x=shipExplanation(dashboard.fire||{});drawer.hidden=false;drawerTitle.textContent='STATO NAVE';drawerBody.innerHTML=section("COS'È",x.what)+section('STATO ADESSO',x.now)+section('PERCHÉ',x.why)+section("COSA C'È DENTRO",'EMAIL indica il cannone email. FORM indica il fuoco delle candidature via form. RUNTIME indica se il motore operativo FORM è attivo.')+actionButtons(x.actions,'Stato nave')}
function prepareDraft(action,context){const box=$('commandDraft');if(!box)return;if(action==='Chiedi a GPT')box.value=`Spiegami ${context}: cosa sta succedendo, perché e cosa richiede attenzione.`;else if(action==='Prepara ordine')box.value=`Ordine su ${context}: `;else box.value=`Apri e spiegami ${context}.`;box.focus()}
document.addEventListener('click',e=>{const m=e.target.closest('.metric');if(m)openMetric(m.dataset.key);const n=e.target.closest('.navBtn');if(n)renderGroup(n.dataset.group);const a=e.target.closest('.actionBtn');if(a)prepareDraft(a.dataset.action,a.dataset.context)});
$('refresh').onclick=openDashboard;retry.onclick=()=>location.reload();enter.onclick=enroll;code.addEventListener('keydown',e=>{if(e.key==='Enter')enroll()});closeDrawer.onclick=()=>drawer.hidden=true;drawer.addEventListener('click',e=>{if(e.target===drawer)drawer.hidden=true});shipStatus.onclick=openShipStatus;
(async()=>{if(new URLSearchParams(location.search).get('reset')==='1'){localStorage.removeItem(DK);clearSession()}const q=await sessionFromDevice();if(q.kind==='OK')return openDashboard();if(q.kind==='NO_DEVICE'||q.kind==='REVOKED')return showGate();showError('Starship non raggiungibile. Il telefono resta autorizzato. '+(q.message||''))})();
